import './globals.css'
import Sidebar from '@/components/Sidebar'
import InfoSection from '@/components/InfoSection'
import "swiper/swiper.min.css";
import "react-toastify/dist/ReactToastify.css";




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex bg-[#222222] text-[#F5F4F4] '>
        <div className='w-[100px] '>
          <Sidebar />
        </div>
        <div className=' bg-[#444444] w-[570px]'>
          <InfoSection />
        </div>
        <div className='h-screen overflow-scroll overflow-x-hidden w-full'>
          {children}
        </div>
      </body>
    </html>
  )
}


export default  RootLayout